(defn p29
  "How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?"
  [lo hi]
  (let [rng (range 2 (inc hi))]
    (count (sort (distinct (for [a rng b rng] (expt a b)))))))